package com.example.malaysiaitinerary.ui.theme

import androidx.compose.ui.graphics.Color

// Travel & Adventure Color Scheme (Blue, Teal, Gold)
// Professional Travel Theme (Based on Screenshots)
val md_theme_light_primary = Color(0xFF007BFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE7F1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF00A693)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0F2F1)
val md_theme_light_onSecondaryContainer = Color(0xFF00201D)
val md_theme_light_tertiary = Color(0xFFDB8D1B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFF3E0)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F9FA)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFF1F3F4)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9ECAFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF007BFF)
val md_theme_light_outlineVariant = Color(0xFFC3C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9ECAFF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFF82D3C8)
val md_theme_dark_onSecondary = Color(0xFF003732)
val md_theme_dark_secondaryContainer = Color(0xFF005049)
val md_theme_dark_onSecondaryContainer = Color(0xFF9EF0E4)
val md_theme_dark_tertiary = Color(0xFFDFBD78)
val md_theme_dark_onTertiary = Color(0xFF3E2D00)
val md_theme_dark_tertiaryContainer = Color(0xFF574400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFBE1AB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF00629D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9ECAFF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)

// Explorer Design System Colors
val ExplorerPrimary = Color(0xFF003345)
val ExplorerSecondary = Color(0xFF006972)
val ExplorerTertiary = Color(0xFF5C1400)
val ExplorerBackground = Color(0xFFF8F9FA)
val ExplorerSurface = Color(0xFFFFFFFF)
val ExplorerOnPrimary = Color(0xFFFFFFFF)
val ExplorerOnSecondary = Color(0xFFFFFFFF)
val ExplorerOnSurface = Color(0xFF191C1D)
val ExplorerSurfaceContainerLow = Color(0xFFF3F4F5)
val ExplorerSurfaceContainerHigh = Color(0xFFE7E8E9)
val ExplorerSurfaceContainerHighest = Color(0xFFE1E3E4)
val ExplorerSurfaceContainerLowest = Color(0xFFFFFFFF)
val ExplorerPrimaryContainer = Color(0xFF004B63)
val ExplorerSecondaryContainer = Color(0xFF8FEEFC)
val ExplorerOnSecondaryContainer = Color(0xFF006D77)
val ExplorerError = Color(0xFFBA1A1A)
val ExplorerOutline = Color(0xFF71787D)
val ExplorerOnSurfaceVariant = Color(0xFF40484C)
val ExplorerOutlineVariant = Color(0xFFC0C7CD)
